/**:
  ros__parameters:
    # Optional overrides:
    # moveit_cpp_cfg: /my/custom/path/to/moveit_cpp.yaml
    # moveit_cpp_srdf: /my/custom/path/to/moveit_cpp.srdf
    # moveit_controller_cfg: /my/custom/path/to/moveit_controllers.yaml
    max_plan_tries: 10 #Set how many plan tries are allowed per trajectory (at least 5 is recommended)

    stockfish_skill_level: 20
    stockfish_contempt: 30

    #board layout
    a1 : [0.1, -0.3, 0.4]
    tile_size : 0.0375
    #Normd vec for x and y (no z as chess pieces normally slide of the table when slanted...)
    orientation: [-1, -1]