site_name: UR5 Chess ROS2
site_url: https://github.com/Mizo330/UR5_plays_chess_ROS2
theme:
  name: readthedocs
nav:
  - Overwiev: index.md
  - Gazebo simulation: gazebo_sim.md
  - ROS2 nodes: ros2_nodes.md
